# Generated by Django 4.2.9 on 2024-04-28 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="title")),
                ("body", models.TextField(blank=True, null=True, verbose_name="body")),
                (
                    "goal",
                    models.CharField(blank=True, max_length=128, verbose_name="goal"),
                ),
                (
                    "creator_email",
                    models.EmailField(max_length=254, verbose_name="creator_email"),
                ),
                (
                    "creator_contact_information",
                    models.CharField(
                        blank=True, verbose_name="creator_contact_information"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posts",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "db_table": "users_posts",
            },
        ),
    ]
