# Generated by Django 4.2.9 on 2024-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
