# Generated by Django 4.2.9 on 2024-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_posts_goal_progress_posts_monobank_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="goal",
        ),
    ]
