# Generated by Django 4.2.9 on 2024-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True, null=True, verbose_name="about_me"),
        ),
    ]
